name: Deploy Image from Semantic Version

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login Okteto
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Okteto namespace
        id: okteto-namespace
        uses: okteto/namespace@latest
        with:
          name: seonglae

      - name: Set env
        shell: bash
        run: |
          cat ${{ steps.okteto-namespace.outputs.kubeconfig }} | base64 > ./kubeconfig
          cat "KUBE_CONFIG=`cat ./kubeconfig`" >> $GITHUB_ENV
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ env.KUBE_CONFIG }}
        with:
          args: get pods

      - name: Set env
        shell: bash
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          build-args: |
            GIT_TAG=${{ env.RELEASE_VERSION }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
